version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile.local
    ports:
      - 8080:8080
    volumes:
      - .:/app
    environment:
      API_PORT: 8080
      REDIS_ADDRESS: localhost:6379
  redis:
    image: redis/redis-stack:7.2.0-v8
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - "./data/redis:/data"
      - "./redis.conf:/etc/redis.conf"
