version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  # lb-db:
  #   image: mysql:5.7
  #   platform: linux/amd64
  #   environment:
  #     MYSQL_DATABASE: moneyeasy
  #     MYSQL_USER:
  #     MYSQL_PASSWORD:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #     MYSQL_ROOT_PASSWORD:
  #   ports:
  #     - 3308:3306
  #   volumes:
  #     - ./db/docker/conf:/etc/mysql/conf.d
  #     - ./db/docker/data:/var/lib/mysql
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
